// Generated by https://quicktype.io

export interface Gem {
  id: number;
  name: string;
  icon: string;
  mapTier: number;
  levelRequired: number;
  baseType: null;
  stackSize: number;
  variant: string;
  prophecyText: null;
  artFilename: null;
  links: number;
  itemClass: number;
  implicitModifiers: any[];
  explicitModifiers: any[];
  flavourText: string;
  corrupted: boolean;
  gemLevel: number;
  gemQuality: number;
  chaosValue: number;
  exaltedValue: number;
  count: number;
}
