// Generated by https://quicktype.io

export interface ItemAPIResponse {
  Amulet: Item[];
  Weapon: WeaponCategories;
  Belt: Item[];
  Body: BodyArmorCategories;
  Boots: ArmorCategories;
  Flask: FlaskCategories;
  Gloves: ArmorCategories;
  Helmet: ArmorCategories;
  Jewel: JewelCategories;
  Quiver: Item[];
  Ring: Item[];
  Shield: ArmorCategories;
}

export interface Item {
  name: string;
  base: string;
  levelReq: number | null;
  variants: { [key: string]: string[] };
  mods: string[];
  corrupted: boolean;
  shaper: boolean;
  elder: boolean;
  icon: string;
}

export interface ArmorCategories {
  Armour: Item[];
  Evasion: Item[];
  'Energy Shield': Item[];
  'Armour/Evasion': Item[];
  'Armour/Energy Shield': Item[];
  'Evasion/Energy Shield': Item[];
}
export interface BodyArmorCategories extends ArmorCategories {
  'Armour/Evasion/Energy Shield': Item[];
}

export interface FlaskCategories {
  Life: Item[];
  Mana: Item[];
  Hybrid: Item[];
  Utility: Item[];
}

export interface JewelCategories {
  Drop: Item[];
  Threshold: Item[];
  Corrupted: Item[];
  'Quest rewards': Item[];
  'Labyrinth rewards': Item[];
}

export interface WeaponCategories {
  'One Handed Axe': Item[];
  'Two Handed Axe': Item[];
  Bow: Item[];
  Claw: Item[];
  Dagger: Item[];
  'One Handed Mace': Item[];
  Sceptre: Item[];
  'Two Handed Mace': Item[];
  Staff: Item[];
  'One Handed Sword': Item[];
  'Thrusting Sword': Item[];
  'Two Handed Sword': Item[];
  Wand: Item[];
}
